package com.fizzware.dramaticdoors.compat.registries;

import com.fizzware.dramaticdoors.compat.DDCompatAdvancement;
import com.fizzware.dramaticdoors.compat.DDCompatRecipe;
import com.fizzware.dramaticdoors.registry.DDNames;
import com.fizzware.dramaticdoors.registry.DDRegistry;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.state.properties.BlockSetType;

public class BWGCompat
{
	public static void registerCompat() {
		registerBlocksItems();
		registerRecipes();
	}
	
	private static void registerBlocksItems() {
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_ASPEN, DDNames.SHORT_BWG_ASPEN, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_BAOBAB, DDNames.SHORT_BWG_BAOBAB, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobab_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_BLUE_ENCHANTED, DDNames.SHORT_BWG_BLUE_ENCHANTED, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_BULBIS, DDNames.SHORT_BWG_BULBIS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "bulbis_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_CIKA, DDNames.SHORT_BWG_CIKA, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_CYPRESS, DDNames.SHORT_BWG_CYPRESS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cypress_door")), BlockSetType.MANGROVE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_EBONY, DDNames.SHORT_BWG_EBONY, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_EMBUR, DDNames.SHORT_BWG_EMBUR, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "embur_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_ETHER, DDNames.SHORT_BWG_ETHER, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ether_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_FIR, DDNames.SHORT_BWG_FIR, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_FLORUS, DDNames.SHORT_BWG_FLORUS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "florus_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_GREEN_ENCHANTED, DDNames.SHORT_BWG_GREEN_ENCHANTED, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_HOLLY, DDNames.SHORT_BWG_HOLLY, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_IMPARIUS, DDNames.SHORT_BWG_IMPARIUS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "imparius_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_IRONWOOD, DDNames.SHORT_BWG_IRONWOOD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_JACARANDA, DDNames.SHORT_BWG_JACARANDA, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_MAHOGANY, DDNames.SHORT_BWG_MAHOGANY, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_MAPLE, DDNames.SHORT_BWG_MAPLE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_NIGHTSHADE, DDNames.SHORT_BWG_NIGHTSHADE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "nightshade_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_PALM, DDNames.SHORT_BWG_PALM, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_door")), BlockSetType.JUNGLE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_PINE, DDNames.SHORT_BWG_PINE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_RAINBOW_EUCALYPTUS, DDNames.SHORT_BWG_RAINBOW_EUCALYPTUS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_REDWOOD, DDNames.SHORT_BWG_REDWOOD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_SAKURA, DDNames.SHORT_BWG_SAKURA, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_door")), BlockSetType.CHERRY, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_SKYRIS, DDNames.SHORT_BWG_SKYRIS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyris_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_SYTHIAN, DDNames.SHORT_BWG_SYTHIAN, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sythian_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_WHITE_MANGROVE, DDNames.SHORT_BWG_WHITE_MANGROVE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door")), BlockSetType.MANGROVE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_WILLOW, DDNames.SHORT_BWG_WILLOW, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_door")), BlockSetType.MANGROVE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_WITCH_HAZEL, DDNames.SHORT_BWG_WITCH_HAZEL, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_ZELKOVA, DDNames.SHORT_BWG_ZELKOVA, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_door")), BlockSetType.OAK, true);
	}
	
	private static void registerRecipes() {
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_ASPEN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_BAOBAB, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobab_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_BLUE_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_BULBIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "bulbis_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_CIKA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_CYPRESS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cypress_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_EBONY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_EMBUR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "embur_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_ETHER, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ether_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_FIR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_FLORUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "florus_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_GREEN_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_HOLLY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_IMPARIUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "imparius_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_IRONWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_JACARANDA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_MAHOGANY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_MAPLE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_NIGHTSHADE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "nightshade_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_PALM, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_PINE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_RAINBOW_EUCALYPTUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_REDWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_SAKURA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_SKYRIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyris_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_SYTHIAN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sythian_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_WHITE_MANGROVE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_WILLOW, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_WITCH_HAZEL, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_ZELKOVA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_ASPEN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_BAOBAB, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobab_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_BLUE_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_BULBIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "bulbis_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_CIKA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_CYPRESS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cypress_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_EBONY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_EMBUR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "embur_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_ETHER, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ether_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_FIR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_FLORUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "florus_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_GREEN_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_HOLLY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_IMPARIUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "imparius_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_IRONWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_JACARANDA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_MAHOGANY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_MAPLE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_NIGHTSHADE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "nightshade_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_PALM, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_PINE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_RAINBOW_EUCALYPTUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_REDWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_SAKURA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_SKYRIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyris_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_SYTHIAN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sythian_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_WHITE_MANGROVE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_WILLOW, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_WITCH_HAZEL, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_ZELKOVA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_door"));
		
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_ASPEN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_BAOBAB, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobab_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_BLUE_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_BULBIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "bulbis_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_CIKA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_CYPRESS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cypress_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_EBONY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_EMBUR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "embur_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_ETHER, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ether_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_FIR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_FLORUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "florus_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_GREEN_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_HOLLY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_IMPARIUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "imparius_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_IRONWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_JACARANDA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_MAHOGANY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_MAPLE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_NIGHTSHADE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "nightshade_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_PALM, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_PINE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_RAINBOW_EUCALYPTUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_REDWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_SKYRIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyris_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_SAKURA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_SYTHIAN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sythian_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_WHITE_MANGROVE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_WILLOW, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_WITCH_HAZEL, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_ZELKOVA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_door"), true);
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_ASPEN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_BAOBAB, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobab_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_BLUE_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_BULBIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "bulbis_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_CIKA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_CYPRESS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cypress_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_EBONY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_EMBUR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "embur_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_ETHER, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ether_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_FIR, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_FLORUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "florus_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_GREEN_ENCHANTED, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_HOLLY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_IMPARIUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "imparius_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_IRONWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_JACARANDA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_MAHOGANY, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_MAPLE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_NIGHTSHADE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "nightshade_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_PALM, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_PINE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_RAINBOW_EUCALYPTUS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_REDWOOD, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_SAKURA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_SKYRIS, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyris_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_SYTHIAN, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sythian_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_WHITE_MANGROVE, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_WILLOW, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_WITCH_HAZEL, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_ZELKOVA, ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_door"), "tall_bwg_wooden_door");
	}
}
