package com.fizzware.dramaticdoors.compat.registries;

import com.fizzware.dramaticdoors.compat.DDCompatAdvancement;
import com.fizzware.dramaticdoors.compat.DDCompatRecipe;
import com.fizzware.dramaticdoors.registry.DDNames;
import com.fizzware.dramaticdoors.registry.DDRegistry;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.state.properties.BlockSetType;

public class MoreDoorsCompat {
	
	public static void registerCompat() {
		registerBlocksItems();
		registerRecipes();
	}
	
	private static void registerBlocksItems() {
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_GLASS, DDNames.SHORT_MD_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_TINTED_GLASS, DDNames.SHORT_MD_TINTED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "tinted_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BLACK_STAINED_GLASS, DDNames.SHORT_MD_BLACK_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "black_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_GRAY_STAINED_GLASS, DDNames.SHORT_MD_GRAY_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "gray_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_LIGHT_GRAY_STAINED_GLASS, DDNames.SHORT_MD_LIGHT_GRAY_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "light_gray_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_WHITE_STAINED_GLASS, DDNames.SHORT_MD_WHITE_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "white_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_RED_STAINED_GLASS, DDNames.SHORT_MD_RED_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "red_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_ORANGE_STAINED_GLASS, DDNames.SHORT_MD_ORANGE_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "orange_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_YELLOW_STAINED_GLASS, DDNames.SHORT_MD_YELLOW_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "yellow_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_LIME_STAINED_GLASS, DDNames.SHORT_MD_LIME_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "lime_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_GREEN_STAINED_GLASS, DDNames.SHORT_MD_GREEN_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "green_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_CYAN_STAINED_GLASS, DDNames.SHORT_MD_CYAN_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "cyan_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BLUE_STAINED_GLASS, DDNames.SHORT_MD_BLUE_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "blue_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_PURPLE_STAINED_GLASS, DDNames.SHORT_MD_PURPLE_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "purple_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_MAGENTA_STAINED_GLASS, DDNames.SHORT_MD_MAGENTA_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "magenta_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_PINK_STAINED_GLASS, DDNames.SHORT_MD_PINK_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "pink_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_LIGHT_BLUE_STAINED_GLASS, DDNames.SHORT_MD_LIGHT_BLUE_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "light_blue_stained_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BROWN_STAINED_GLASS, DDNames.SHORT_MD_BROWN_STAINED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "brown_stained_glass_door")), BlockSetType.STONE, true);

		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_COAL, DDNames.SHORT_MD_COAL, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "coal_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_GOLD, DDNames.SHORT_MD_GOLD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "gold_door")), BlockSetType.IRON, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_NETHERITE, DDNames.SHORT_MD_NETHERITE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "netherite_door")), BlockSetType.IRON, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_DIAMOND, DDNames.SHORT_MD_DIAMOND, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "diamond_door")), BlockSetType.IRON, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_EMERALD, DDNames.SHORT_MD_EMERALD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "emerald_door")), BlockSetType.IRON, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_LAPIS, DDNames.SHORT_MD_LAPIS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "lapis_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_REDSTONE, DDNames.SHORT_MD_REDSTONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "redstone_door")), BlockSetType.STONE, true);

		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_ANDESITE, DDNames.SHORT_MD_ANDESITE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "andesite_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_AMETHYST, DDNames.SHORT_MD_AMETHYST, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "amethyst_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BASALT, DDNames.SHORT_MD_BASALT, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "basalt_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BEDROCK, DDNames.SHORT_MD_BEDROCK, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "bedrock_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BLACKSTONE, DDNames.SHORT_MD_BLACKSTONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "blackstone_door")), BlockSetType.POLISHED_BLACKSTONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_CALCITE, DDNames.SHORT_MD_CALCITE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "calcite_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_COBBLESTONE, DDNames.SHORT_MD_COBBLESTONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "cobblestone_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_COBBLED_DEEPSLATE, DDNames.SHORT_MD_COBBLED_DEEPSLATE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "cobbled_deepslate_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_POLISHED_DEEPSLATE, DDNames.SHORT_MD_POLISHED_DEEPSLATE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "polished_deepslate_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_DIORITE, DDNames.SHORT_MD_DIORITE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "diorite_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_DRIPSTONE, DDNames.SHORT_MD_DRIPSTONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "dripstone_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_END_STONE, DDNames.SHORT_MD_END_STONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "end_stone_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_GRANITE, DDNames.SHORT_MD_GRANITE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "granite_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_NETHERRACK, DDNames.SHORT_MD_NETHERRACK, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "netherrack_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_OBSIDIAN, DDNames.SHORT_MD_OBSIDIAN, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "obsidian_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_PURPUR, DDNames.SHORT_MD_PURPUR, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "purpur_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_PRISMARINE, DDNames.SHORT_MD_PRISMARINE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "prismarine_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_QUARTZ, DDNames.SHORT_MD_QUARTZ, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "quartz_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_SANDSTONE, DDNames.SHORT_MD_SANDSTONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "sandstone_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_RED_SANDSTONE, DDNames.SHORT_MD_RED_SANDSTONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "red_sandstone_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_STONE, DDNames.SHORT_MD_STONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "stone_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_SMOOTH_STONE, DDNames.SHORT_MD_SMOOTH_STONE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "smooth_stone_door")), BlockSetType.STONE, true);

		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BOOKSHELF, DDNames.SHORT_MD_BOOKSHELF, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "bookshelf_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_BRICK, DDNames.SHORT_MD_BRICK, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "brick_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_NETHER_BRICK, DDNames.SHORT_MD_NETHER_BRICK, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "nether_brick_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_MUD_BRICK, DDNames.SHORT_MD_MUD_BRICK, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "mud_brick_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_ICE, DDNames.SHORT_MD_ICE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "ice_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_MUD, DDNames.SHORT_MD_MUD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "mud_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_SCULK, DDNames.SHORT_MD_SCULK, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "sculk_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MD_SPONGE, DDNames.SHORT_MD_SPONGE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("moredoors", "sponge_door")), BlockSetType.OAK, true);
	}
	
	private static void registerRecipes() {
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "tinted_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BLACK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "black_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "gray_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_LIGHT_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_gray_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_WHITE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "white_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_RED_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "red_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_ORANGE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "orange_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_YELLOW_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "yellow_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_LIME_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "lime_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_GREEN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "green_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_CYAN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "cyan_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "blue_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_PURPLE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "purple_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_MAGENTA_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "magenta_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_PINK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "pink_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_LIGHT_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_blue_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BROWN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "brown_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_COAL, ResourceLocation.fromNamespaceAndPath("moredoors", "coal_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_GOLD, ResourceLocation.fromNamespaceAndPath("moredoors", "gold_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_NETHERITE, ResourceLocation.fromNamespaceAndPath("moredoors", "netherite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_DIAMOND, ResourceLocation.fromNamespaceAndPath("moredoors", "diamond_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_EMERALD, ResourceLocation.fromNamespaceAndPath("moredoors", "emerald_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_LAPIS, ResourceLocation.fromNamespaceAndPath("moredoors", "lapis_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_REDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "redstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_ANDESITE, ResourceLocation.fromNamespaceAndPath("moredoors", "andesite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_AMETHYST, ResourceLocation.fromNamespaceAndPath("moredoors", "amethyst_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BASALT, ResourceLocation.fromNamespaceAndPath("moredoors", "basalt_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BEDROCK, ResourceLocation.fromNamespaceAndPath("moredoors", "bedrock_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BLACKSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "blackstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_CALCITE, ResourceLocation.fromNamespaceAndPath("moredoors", "calcite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_COBBLESTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobblestone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_COBBLED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobbled_deepslate_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_POLISHED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "polished_deepslate_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_DIORITE, ResourceLocation.fromNamespaceAndPath("moredoors", "diorite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_DRIPSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "dripstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_END_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "end_stone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_GRANITE, ResourceLocation.fromNamespaceAndPath("moredoors", "granite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_NETHERRACK, ResourceLocation.fromNamespaceAndPath("moredoors", "netherrack_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_OBSIDIAN, ResourceLocation.fromNamespaceAndPath("moredoors", "obsidian_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_PURPUR, ResourceLocation.fromNamespaceAndPath("moredoors", "purpur_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_PRISMARINE, ResourceLocation.fromNamespaceAndPath("moredoors", "prismarine_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_QUARTZ, ResourceLocation.fromNamespaceAndPath("moredoors", "quartz_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "sandstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_RED_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "red_sandstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "stone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_SMOOTH_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "smooth_stone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BOOKSHELF, ResourceLocation.fromNamespaceAndPath("moredoors", "bookshelf_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "brick_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_NETHER_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "nether_brick_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_MUD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_brick_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_ICE, ResourceLocation.fromNamespaceAndPath("moredoors", "ice_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_MUD, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_SCULK, ResourceLocation.fromNamespaceAndPath("moredoors", "sculk_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MD_SPONGE, ResourceLocation.fromNamespaceAndPath("moredoors", "sponge_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "tinted_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BLACK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "black_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "gray_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_LIGHT_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_gray_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_WHITE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "white_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_RED_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "red_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_ORANGE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "orange_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_YELLOW_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "yellow_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_LIME_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "lime_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_GREEN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "green_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_CYAN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "cyan_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "blue_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_PURPLE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "purple_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_MAGENTA_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "magenta_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_PINK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "pink_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_LIGHT_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_blue_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BROWN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "brown_stained_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_COAL, ResourceLocation.fromNamespaceAndPath("moredoors", "coal_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_GOLD, ResourceLocation.fromNamespaceAndPath("moredoors", "gold_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_NETHERITE, ResourceLocation.fromNamespaceAndPath("moredoors", "netherite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_DIAMOND, ResourceLocation.fromNamespaceAndPath("moredoors", "diamond_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_EMERALD, ResourceLocation.fromNamespaceAndPath("moredoors", "emerald_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_LAPIS, ResourceLocation.fromNamespaceAndPath("moredoors", "lapis_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_REDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "redstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_ANDESITE, ResourceLocation.fromNamespaceAndPath("moredoors", "andesite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_AMETHYST, ResourceLocation.fromNamespaceAndPath("moredoors", "amethyst_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BASALT, ResourceLocation.fromNamespaceAndPath("moredoors", "basalt_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BEDROCK, ResourceLocation.fromNamespaceAndPath("moredoors", "bedrock_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BLACKSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "blackstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_CALCITE, ResourceLocation.fromNamespaceAndPath("moredoors", "calcite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_COBBLESTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobblestone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_COBBLED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobbled_deepslate_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_POLISHED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "polished_deepslate_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_DIORITE, ResourceLocation.fromNamespaceAndPath("moredoors", "diorite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_DRIPSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "dripstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_END_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "end_stone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_GRANITE, ResourceLocation.fromNamespaceAndPath("moredoors", "granite_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_NETHERRACK, ResourceLocation.fromNamespaceAndPath("moredoors", "netherrack_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_OBSIDIAN, ResourceLocation.fromNamespaceAndPath("moredoors", "obsidian_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_PURPUR, ResourceLocation.fromNamespaceAndPath("moredoors", "purpur_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_PRISMARINE, ResourceLocation.fromNamespaceAndPath("moredoors", "prismarine_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_QUARTZ, ResourceLocation.fromNamespaceAndPath("moredoors", "quartz_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "sandstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_RED_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "red_sandstone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "stone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_SMOOTH_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "smooth_stone_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BOOKSHELF, ResourceLocation.fromNamespaceAndPath("moredoors", "bookshelf_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "brick_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_NETHER_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "nether_brick_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_MUD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_brick_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_ICE, ResourceLocation.fromNamespaceAndPath("moredoors", "ice_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_MUD, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_SCULK, ResourceLocation.fromNamespaceAndPath("moredoors", "sculk_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MD_SPONGE, ResourceLocation.fromNamespaceAndPath("moredoors", "sponge_door"));
		
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "tinted_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BLACK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "black_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "gray_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_LIGHT_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_gray_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_WHITE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "white_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_RED_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "red_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_ORANGE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "orange_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_YELLOW_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "yellow_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_LIME_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "lime_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_GREEN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "green_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_CYAN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "cyan_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "blue_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_PURPLE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "purple_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_MAGENTA_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "magenta_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_PINK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "pink_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_LIGHT_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_blue_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BROWN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "brown_stained_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_COAL, ResourceLocation.fromNamespaceAndPath("moredoors", "coal_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_GOLD, ResourceLocation.fromNamespaceAndPath("moredoors", "gold_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_NETHERITE, ResourceLocation.fromNamespaceAndPath("moredoors", "netherite_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_DIAMOND, ResourceLocation.fromNamespaceAndPath("moredoors", "diamond_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_EMERALD, ResourceLocation.fromNamespaceAndPath("moredoors", "emerald_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_LAPIS, ResourceLocation.fromNamespaceAndPath("moredoors", "lapis_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_REDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "redstone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_ANDESITE, ResourceLocation.fromNamespaceAndPath("moredoors", "andesite_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_AMETHYST, ResourceLocation.fromNamespaceAndPath("moredoors", "amethyst_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BASALT, ResourceLocation.fromNamespaceAndPath("moredoors", "basalt_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BEDROCK, ResourceLocation.fromNamespaceAndPath("moredoors", "bedrock_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BLACKSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "blackstone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_CALCITE, ResourceLocation.fromNamespaceAndPath("moredoors", "calcite_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_COBBLESTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobblestone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_COBBLED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobbled_deepslate_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_POLISHED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "polished_deepslate_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_DIORITE, ResourceLocation.fromNamespaceAndPath("moredoors", "diorite_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_DRIPSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "dripstone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_END_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "end_stone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_GRANITE, ResourceLocation.fromNamespaceAndPath("moredoors", "granite_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_NETHERRACK, ResourceLocation.fromNamespaceAndPath("moredoors", "netherrack_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_OBSIDIAN, ResourceLocation.fromNamespaceAndPath("moredoors", "obsidian_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_PURPUR, ResourceLocation.fromNamespaceAndPath("moredoors", "purpur_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_PRISMARINE, ResourceLocation.fromNamespaceAndPath("moredoors", "prismarine_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_QUARTZ, ResourceLocation.fromNamespaceAndPath("moredoors", "quartz_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "sandstone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_RED_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "red_sandstone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "stone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_SMOOTH_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "smooth_stone_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BOOKSHELF, ResourceLocation.fromNamespaceAndPath("moredoors", "bookshelf_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "brick_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_NETHER_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "nether_brick_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_MUD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_brick_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_ICE, ResourceLocation.fromNamespaceAndPath("moredoors", "ice_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_MUD, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_SCULK, ResourceLocation.fromNamespaceAndPath("moredoors", "sculk_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MD_SPONGE, ResourceLocation.fromNamespaceAndPath("moredoors", "sponge_door"), true);
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "tinted_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BLACK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "black_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "gray_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_LIGHT_GRAY_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_gray_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_WHITE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "white_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_RED_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "red_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_ORANGE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "orange_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_YELLOW_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "yellow_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_LIME_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "lime_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_GREEN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "green_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_CYAN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "cyan_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "blue_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_PURPLE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "purple_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_MAGENTA_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "magenta_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_PINK_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "pink_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_LIGHT_BLUE_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "light_blue_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BROWN_STAINED_GLASS, ResourceLocation.fromNamespaceAndPath("moredoors", "brown_stained_glass_door"), "tall_md_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_COAL, ResourceLocation.fromNamespaceAndPath("moredoors", "coal_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_GOLD, ResourceLocation.fromNamespaceAndPath("moredoors", "gold_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_NETHERITE, ResourceLocation.fromNamespaceAndPath("moredoors", "netherite_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_DIAMOND, ResourceLocation.fromNamespaceAndPath("moredoors", "diamond_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_EMERALD, ResourceLocation.fromNamespaceAndPath("moredoors", "emerald_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_LAPIS, ResourceLocation.fromNamespaceAndPath("moredoors", "lapis_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_REDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "redstone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_ANDESITE, ResourceLocation.fromNamespaceAndPath("moredoors", "andesite_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_AMETHYST, ResourceLocation.fromNamespaceAndPath("moredoors", "amethyst_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BASALT, ResourceLocation.fromNamespaceAndPath("moredoors", "basalt_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BEDROCK, ResourceLocation.fromNamespaceAndPath("moredoors", "bedrock_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BLACKSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "blackstone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_CALCITE, ResourceLocation.fromNamespaceAndPath("moredoors", "calcite_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_COBBLESTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobblestone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_COBBLED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "cobbled_deepslate_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_POLISHED_DEEPSLATE, ResourceLocation.fromNamespaceAndPath("moredoors", "polished_deepslate_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_DIORITE, ResourceLocation.fromNamespaceAndPath("moredoors", "diorite_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_DRIPSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "dripstone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_END_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "end_stone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_GRANITE, ResourceLocation.fromNamespaceAndPath("moredoors", "granite_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_NETHERRACK, ResourceLocation.fromNamespaceAndPath("moredoors", "netherrack_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_OBSIDIAN, ResourceLocation.fromNamespaceAndPath("moredoors", "obsidian_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_PURPUR, ResourceLocation.fromNamespaceAndPath("moredoors", "purpur_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_PRISMARINE, ResourceLocation.fromNamespaceAndPath("moredoors", "prismarine_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_QUARTZ, ResourceLocation.fromNamespaceAndPath("moredoors", "quartz_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "sandstone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_RED_SANDSTONE, ResourceLocation.fromNamespaceAndPath("moredoors", "red_sandstone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "stone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_SMOOTH_STONE, ResourceLocation.fromNamespaceAndPath("moredoors", "smooth_stone_door"), "tall_md_stone_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BOOKSHELF, ResourceLocation.fromNamespaceAndPath("moredoors", "bookshelf_door"), "tall_misc_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "brick_door"), "tall_brick_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_NETHER_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "nether_brick_door"), "tall_brick_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_MUD_BRICK, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_brick_door"), "tall_brick_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_ICE, ResourceLocation.fromNamespaceAndPath("moredoors", "ice_door"), "tall_misc_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_MUD, ResourceLocation.fromNamespaceAndPath("moredoors", "mud_door"), "tall_misc_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_SCULK, ResourceLocation.fromNamespaceAndPath("moredoors", "sculk_door"), "tall_misc_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MD_SPONGE, ResourceLocation.fromNamespaceAndPath("moredoors", "sponge_door"), "tall_misc_door");
	}
}
